### PR TITLE
Add link for techradar.io

### PR DESCRIPTION
**Pull request by andyw8**
I've just open-sourced the code behind [techradar.io](http://techradar.io), a tool for building and sharing your own Technology Radar.

### CODE REVIEW

**Comment by divanvisagie** [comment]
My chrome doesn't like that ssl cert

**Comment by andyw8** [comment]
I've updated the link to point to the http site until a proper SSL certificate is in place.

**Comment by philoserf** [comment]
@andyw8 You didn't update the link in your first comment on this PR. It is still an https URL.

**Comment by andyw8** [comment]
@philoserf thanks, I've updated it.

**Comment by philoserf** [comment]
We should close the issue as the fix is in.

**Comment by philoserf** [comment]
Can we please close this @bdargan . I'd like for it to no longer display under my active "Pull Requests"  mentions since this is done.

**Pull request merged**
