### PR TITLE
Support different numbers of "quadrants" in technology radar

### PR DESCRIPTION
**Pull request by fffej**
I was using this (excellent!) tool to create a technology radar for internal use. I could only think of three appropriate quadrants, so this pull request improves the support for that by not drawing a 2x2 grid in the middle of the circle, instead drawing the appropriate number of lines outwards from the center of the arc.

I've probably explained that poorly, so here's a picture of a technology radar with three quadrants (quadrants is now poorly named, but I didn't want to make the commit noisy!).

721c3570-2111-11e3-8be8-2767da48d40b

Apologies for the other hideous pull request (hey, at least I learnt to do things on a branch).

### CODE REVIEW

**Comment by NetAppBlueDevil** [comment]
Nice change.  I might need the same.

How did you handle the listing of the labels around the bullseye?

**Comment by fffej** [comment]
Can you show an example of what it doesn't do?

**Comment by NetAppBlueDevil** [comment]
I was trying to build a radar from scratch.  I needed to have an item in the inner arc of a quadrant if I had anything in the quadrant.

So try with just a second arc point in one quadrant.

daniel

**Comment by NetAppBlueDevil** [comment]
Here’s a data file that I have.  (I.ve also modified to 75 point arc from 100 for screen fit.  That also needs this change in radar.js to substitute the hard coded 100 with radar_arc_size variable I added in the data.

91     var itemsByStage = _.groupBy(radar_data[i].items, function(item) {return Math.floor(item.pc.r / 100)});

In running this this pull request changes also
https://github.com/bdargan/techradar/pull/9/files

It works better.  I get the upper left quadrant drawn.  But only one dot item is appearing in the upper right quadrant.  See attached image

Hopefully this is a good test scenario for the issue I’ve got.

Thanks

Daniel

**Pull request closed without merging**
